config/routes.rb
Rails.application.routes.draw do
  resources :product_categories
  root 'home#index'
  resources :home
  resources :products
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord

  validates :name, presence: true, length: {minimum: 2}
  validates :description, presence: true, length: {minimum: 2}

end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry

  has_many :product_categories, dependent: :delete_all
  has_many :products, through: :product_categories

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories, dependent: :destroy

  validates :name, presence: true, length: { minimum:2 }
  validates :description, presence: true
  validates :price, presence: true
  validates :compatibility, presence: true
  validates :feature, presence: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product, :class_name => 'Product', optional: true
  belongs_to :category, :class_name => 'Category', optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true, length: { minimum: 2}
  validates :surname, presence: true, length: { minimum: 2 }
  validates :phone, presence: true, length: { minimum: 10}
  validates :email, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :moderator, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :get_cat
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters # devise gem'inde defaultda gelen user alanlarına ek alan eklediğimizde permit yapmak için
    attributes = [:name, :surname, :phone]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
  def get_cat
    # kategoriler burada çekilecek
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price, :compatibility, :feature)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end

app/views/home/index.html.erb
<div class="container">
  <%= render 'shared/slider' %>
  <div class="row">
    <% @products.each do |p| %>
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">
            <h3> <%= p.name %> </h3>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-4">
                <img src="https://dosya.turkmmo.com/2020/08/31970_1e14f2f1e49479f32f4a50c57603251b.png" width="100%">
              </div>
              <div class="col-md-8">
                <p> <strong>Ürün ismi:</strong> <%= p.name %> </p>
                <p> <strong>Ürün Kategorisi:</strong><%= p.product_categories.first.category.name %> </p>
<!--                <p> <strong>Marka:</strong><%#= p.brand.name %> </p>-->
                <p> <strong>Fiyat:</strong><%= p.price %> TL</p>
                <p> <strong>Ürün Açıklaması:</strong><%= p.description %> </p>
                <p> <strong>Ürün Uyumu:</strong><%= p.compatibility %> </p>
              </div>
            </div>
            <div class="d-grid gap-2">
              <%= link_to "Ürün Detayına Git", product_path(p.id), class:"btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>







<!--<h1>Pages#home</h1>
<p>Find me in app/views/home/index.html.erb</p>
<% if current_user %>
  <p> Hello <%= current_user.email %></p>
  <p>
    You have succesfuly aut
  </p>
  <p>
    you are a [<%= current_user.role %>]
  </p>
  <% if current_user.admin? %>
  <p>Admin ayarları</p>
  <% end %>
  <p>
    <%= link_to "sign out", destroy_user_session_path, 'data-turbo-method': :delete %>
  </p>
<% else %>
  <p>Giriş yapılmamış.</p>
  <%= link_to "Sign up",  new_user_registration_path %>
  <%= link_to "Log in",  new_user_session_path %>
<% end %>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Motospartan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="container">

    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!--<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<% if current_user %>
  <p> Hello <%= current_user.email %></p>
  <p>
    You have succesfuly aut
  </p>
  <p>
    you are a [<%= current_user.role %>]
  </p>
  <% if current_user.admin? %>
  <p>Admin ayarları</p>
  <% end %>
  <p>
    <%= link_to "sign out", destroy_user_session_path, 'data-turbo-method': :delete %>
  </p>
<% else %>
  <p>Giriş yapılmamış.</p>
  <%= link_to "Sign up",  new_user_registration_path %>
  <%= link_to "Log in",  new_user_session_path %>
<% end %>
-->

app/views/products/edit.html.erb
hiii

app/views/products/index.html.erb
<% if current_user and current_user.admin? %>
  <div class="container">
    <h1>All products here!</h1>
    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">İsim</th>
        <th scope="col">Açıklama</th>
        <th scope="col">Fiyat</th>
        <th scope="col">Uyumluluk</th>
        <th scope="col">Özellikler</th>
      </tr>
      </thead>
      <tbody>
      <% @products.each do |p| %>
        <tr>
          <td><%= link_to "#{p.id}", product_path(p.id) %></td>
          <td><%= p.name %></td>
          <td><%= p.description %></td>
          <td><%= p.price %></td>
          <td><%= p.compatibility %></td>
          <td><%= p.feature %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div>
    <%= link_to "Create Product", new_product_path %>
  </div>
<% else %>
  <div class="container">
    <h2 class="mt-5 text-danger">This page for only admins. You are not admin.</h2>
  </div>
<% end %>

app/views/products/new.html.erb
<% if current_user and current_user.admin? %>
  <div class="container">
    <%= form_with model: @product do |f| %>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.label :description %>
        <%= f.text_field :description %>
      </div>
      <div>
        <%= f.label :price %>
        <%= f.text_field :price %>
      </div>
      <div>
        <%= f.label :compatibility %>
        <%= f.text_field :compatibility %>
      </div>
      <div>
        <%= f.label :feature %>
        <%= f.text_field :feature %>
      </div>
      <div>
        <%= f.submit %>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="container">
    <h2 class="mt-5 text-danger">This page for only admins. You are not admin.</h2>
  </div>
<% end %>

app/views/products/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-5">
      <img src="https://dosya.turkmmo.com/2020/08/31970_1e14f2f1e49479f32f4a50c57603251b.png" width="100%">
    </div>
    <div class="col-md-7">
      <table class="table table-striped">
        <tbody>
          <tr>
            <td>İsim: <%= @product.name %></td>
          </tr>
          <tr>
            <td>Fiyat: <%= @product.price %></td>
          </tr>
          <tr>
            <td>Açıklama: <%= @product.description %></td>
          </tr>
          <tr>
            <td>Uyumluluk: <%= @product.compatibility %></td>
          </tr>
          <tr>
            <td>Özellikler: <%= @product.feature %></td>
          </tr>
          <tr>
            <td>
              <div class="d-grid gap-2">
                <%= link_to "Sepete Ekle", product_path(@product.id), class:"btn btn-success" %>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "AKTEMUR", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
<!--    <div class="collapse navbar-collapse" id="navbarNav">-->
<!--      <ul class="navbar-nav">-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link active" aria-current="page" href="#">Home</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Features</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Pricing</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--        </li>-->
<!--      </ul>-->
<!--    </div>-->
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Buradan Arayın" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Ara</button>
    </form>
    <div>
      <% if current_user %>
        <span class="text-white">Hoşgeldiniz <%= link_to current_user.name, edit_user_registration_path %></span>
        <%= link_to "Çıkış Yap", destroy_user_session_path, 'data-turbo-method': :delete, class: "btn btn-danger ms-2" %>
      <% else %>
        <%= link_to "Üye Ol!", new_user_registration_path, class: "btn btn-primary" %>
        <%= link_to "Giriş Yap!", new_user_session_path, class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_slider.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag 'slider1.jpg', :class => "d-block w-100", :style => "max-height:400px;" %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider2.jpg', :class => "d-block w-100", :style => "max-height:400px;" %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>